version: '3.9'

services:
  database:
    build: ./db
    container_name: database
    env_file:
      - db/.env
    ports:
      - "3306:3306"
    expose:
      - 3306
  app:
    build: .
    container_name: application
    env_file: .env
