version: '3.9'

services:
  database-test:
    build: ./db
    container_name: database-test
    env_file:
      - .env
    ports:
      - "3306:3306"
    expose:
      - 3306
  app-test:
    build: .
    container_name: application-test
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@database-test:3306/${MYSQL_DATABASE}
    command: cargo test
